[Serial]
Name = "COM3"
Baud = 57600
RtsCts = false

[TraceSettings]
#AshTraceOn = true
EzspCallbackTraceOn = true
#EzspFrameTraceOn = true
NcpTraceOn = true
NcpFormTraceOn = true

[NetworkSettings]
NetworkType = "hetu"
SecurityLevel = 0
